# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Systemdump
author: "Xavier Lucas"
description: > # this means to ignore newlines until "baseurl:"
  Technical insights, considerations and stories of the IT sphere told from the
  inside.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.systemdump.org"
twitter:
  username: systemdump
github:
  username: xlucas
linkedin:
  profile: xavier-lucas-01aaa0b2
  username: Xavier Lucas
disqus:
  shortname: systemdump
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
