#######################
# Theme Customization #
#######################

title: Systemdump
author: Xavier Lucas
description: My thoughts, technical insights and experimentations.
url: https://blog.systemdump.org
repo: https://github.com/xlucas/xlucas.github.io

baseurl: ''
banner: /images/banner.svg
avatar: /images/logo.png

disqus:
  shortname: systemdump
twitter:
  username: systemdump

nav_menu:
  - name: Posts
    url: /
    icon: /images/icons.svg#posts
  - name: Projects
    url: /projects
    icon: /images/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/xlucas
    icon: /images/icons.svg#github
    outbound: true
  - name: Twitter
    url: https://twitter.com/systemdump
    icon: /images/icons.svg#twitter
    outbound: true

projects:
  - title: SVFS
    teaser: A Virtual File System for Openstack Swift.
    url: https://github.com/ovh/svfs
    role: Creator
    category: Object Storage


#######
# SEO #
#######


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
